services:
  aw7v2m9q4x:
    container_name: aw7v2m9q4x_app
    image: ghcr.io/mr-devloper005/arcanumwebs.com:latest
    env_file:
      - .env
    network_mode: bridge
    restart: always
    ports:
      - "127.0.0.1:3082:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/"]
      interval: 5m
      timeout: 3s
      retries: 2
